### ISSUE TITLE
[Error] Text' is ambiguous, imported from the namespaces or types 'system system.drawing'.

### ISSUE THREAD

**Issue by Marshall13** [NYAN-x-CAT/Lime-Crypter#1]
Good evening,
At first, I would really like to thank you for sharing a source like this :) It's really generous of you, so many people offer it on condition of paying ... My personal project is to adapt this code in Python, so I do not know much about VB :)

So, could you help me solve this error?
![image](https://user-images.githubusercontent.com/21182039/42827826-957fedf6-89e7-11e8-850e-4fe37ebebf30.png)

Thanks you in advance :)

**Comment by NYAN-x-CAT** [comment]
Try System.Text.StringBuilder

Or re-download SRC, I updated it
