### ISSUE TITLE
The code does not run, error displayed...please help

### ISSUE THREAD

**Issue by findlokiMCU** [NYAN-x-CAT/Lime-Crypter#23]
**the following errors were displayed:**

Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file Forms\FormInformation.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Lime-Crypter		.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file Forms\Form1.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Lime-Crypter			

Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file Forms\FormChangeIcon.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Lime-Crypter

**Comment by NYAN-x-CAT** [comment]
Hello friend.
You have to unblock the file, right click on the file, click Properties, select “Unblock,” and click OK.
