### ISSUE TITLE
Bind file - Once

### ISSUE THREAD

**Issue by TheSilencer** [NYAN-x-CAT/Lime-Crypter#3]
At Bind file there is option "Once", which I guess is to execute Bind file only once? If this is so, than it's bugged, since if you check option "once" Bind file is never opened.

**Comment by NYAN-x-CAT** [comment]
In your TEMP folder, search for file "LimeOnce", and delete it.
You may change this from source code if you want a unique name for every crypted file.

**Comment by TheSilencer** [comment]
After deleting LimeOnce from TEMP folder exe file is not made - last line at build window: "Object reference not set to an instance of an object."

**Comment by NYAN-x-CAT** [comment]
Hello @TheSilencer 

I updated the source, redownload it.

**Comment by TheSilencer** [comment]
It's working now, thank you.
