### ISSUE TITLE
nanocore RAT !

### ISSUE THREAD

**Issue by sparta34** [NYAN-x-CAT/Lime-Crypter#7]
hey man thanks for all those projects but i can't use your crypter with nanocore rat server i have tried all options injections or without injections can you update it please thanks

**Comment by NYAN-x-CAT** [comment]
Hi. This is a educational project and I don't do requests. Specially cracked ones.

**Comment by sparta34** [comment]
yes i know , i want just know i can compile native server bytes using regasm or msbuild that it
