### ISSUE TITLE
I tried it on lime-rat

### ISSUE THREAD

**Issue by cnilsecure** [NYAN-x-CAT/Lime-Crypter#8]
Hi,

I build a limerat client after that i tried to use lime-cryptor but when i try to run the "crypted" client nothing happens (new-client.exe works fine)
any idea what i did wrong?

**Comment by trollmad3** [comment]
Could you go into detail what you mean by 

> nothing happens (new-client.exe works fine)

**Comment by cnilsecure** [comment]
What i meant is when i ran the "lime-rat" client (a.k.a new-client.exe) without lime-crypter it runs fine
but after i use lime-crypter it does not connect anymore.

**Comment by NYAN-x-CAT** [comment]
Tested on limerat. worked without problem

**Comment by trollmad3** [comment]
@cnilsecure im guessing you exported the server then putted it into the crypter?
